/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_renard_glcamera_ImageFilter */

#ifndef _Included_de_renard_glcamera_ImageFilter
#define _Included_de_renard_glcamera_ImageFilter
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_de_renard_glcamera_ImageFilter_nativeUploadTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_renard_glcamera_ImageFilter
 * Method:    nativeProcessImage
 * Signature: ([B)I
 */
JNIEXPORT void JNICALL Java_de_renard_glcamera_ImageFilter_nativeProcessImage
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     de_renard_glcamera_ImageFilter
 * Method:    nativeStart
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_renard_glcamera_ImageFilter_nativeStart
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_renard_glcamera_ImageFilter
 * Method:    nativeEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_renard_glcamera_ImageFilter_nativeEnd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
